--Tietokannan taulujen poistaminen oikeassa järjestyksessä huomoiden PK:t ja FK:t
DROP TABLE ASIOINTI; 
DROP TABLE TYOSKENTELY; 
DROP TABLE VUOKRAAMINEN; 
DROP TABLE VARAAMINEN; 
DROP TABLE VALIKOIMA; 
DROP TABLE VARASTO; 
DROP TABLE VUOKRAUS; 
DROP TABLE VARAUS; 
DROP TABLE TYOVUORO; 
DROP TABLE ASIAKAS; 
DROP TABLE TOIMIPISTE; 
DROP TABLE TYONTEKIJA; 
DROP TABLE OHEISTUOTE; 
DROP TABLE ELOKUVA; 
DROP TABLE POSTITMP; 
